# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: bash -c 'cd src && poetry run black .'
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
        files: ^python/
    -   id: pytest
        name: pytest
        entry: bash -c 'poetry run pytest'
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
